# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='null', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='nombre',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
