# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20170106_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to='../Upload'),
        ),
    ]
