# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0007_auto_20170112_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
    ]
